from dataclasses import dataclass, field

from openhound.core.asset import EdgeDef, NodeDef
from openhound.core.models.entries_dataclass import Edge, EdgePath, EdgeProperties
from pydantic import BaseModel, Field

from openhound_jamf.graph import JAMFAsset, JAMFNode, JAMFNodeProperties
from openhound_jamf.kinds import edges as ek
from openhound_jamf.kinds import nodes as nk
from openhound_jamf.main import app


class User(BaseModel):
    id: int
    name: str


class Site(BaseModel):
    id: int
    name: str


@dataclass
class GroupProperties(JAMFNodeProperties):
    """JAMF Group node properties"""

    site_id: str
    access_level: str
    privilege_objects: list[str]
    privilege_actions: list[str]
    privilege_settings: list[str]
    privilege_set: str
    collected: bool = field(
        default=True, metadata={"description": "Collected/generated by OpenHound"}
    )


class BaseGroup(BaseModel):
    name: str
    id: int


class Privilege(BaseModel):
    jss_objects: list[str] = Field(default_factory=list)
    jss_settings: list[str] = Field(default_factory=list)
    jss_actions: list[str] = Field(default_factory=list)


@app.asset(
    description="Jamf Group asset. Returns a node representing a Jamf Group and edges to its members.",
    node=NodeDef(
        kind=nk.GROUP,
        description="Jamf Group node",
        icon="people-group",
        properties=GroupProperties,
    ),
    edges=[
        EdgeDef(
            start=nk.TENANT,
            end=nk.GROUP,
            kind=ek.CONTAINS,
            description="The tenant contains this group.",
        ),
        EdgeDef(
            start=nk.ACCOUNT,
            end=nk.GROUP,
            kind=ek.MEMBER_OF,
            description="The source account is a member of the group.",
        ),
        EdgeDef(
            start=nk.GROUP,
            end=nk.TENANT,
            kind=ek.ADMIN_TO,
            description="The group has administrative permissions on the tenant.",
            traversable=True,
        ),
        EdgeDef(
            start=nk.GROUP,
            end=nk.SITE,
            kind=ek.ADMIN_TO_SITE,
            description="The group has administrative permissions for the target site.",
            traversable=True,
        ),
        EdgeDef(
            start=nk.GROUP,
            end=nk.TENANT,
            kind=ek.CREATE_ACCOUNTS,
            description="The group can create accounts on the target tenant.",
            traversable=True,
        ),
        EdgeDef(
            start=nk.GROUP,
            end=nk.TENANT,
            kind=ek.UPDATE_ACCOUNTS,
            description="The group can update accounts on the target tenant.",
            traversable=True,
        ),
        EdgeDef(
            start=nk.GROUP,
            end=nk.COMPUTER,
            kind=ek.CREATE_POLICIES,
            description="The group can create policies on the target computer.",
            traversable=True,
        ),
        EdgeDef(
            start=nk.GROUP,
            end=nk.COMPUTER,
            kind=ek.UPDATE_POLICIES,
            description="The group can update policies on the target computer.",
            traversable=True,
        ),
        EdgeDef(
            start=nk.GROUP,
            end=nk.COMPUTER,
            kind=ek.CREATE_COMPUTER_EXTENSIONS,
            description="The group can create extensions on the target computer.",
            traversable=True,
        ),
        EdgeDef(
            start=nk.GROUP,
            end=nk.COMPUTER,
            kind=ek.UPDATE_COMPUTER_EXTENSIONS,
            description="The group can update extensions on the target computer.",
            traversable=True,
        ),
        EdgeDef(
            start=nk.GROUP,
            end=nk.TENANT,
            kind=ek.SCRIPTS_NON_TRAVERSABLE,
            description="The group can create or update scripts on the target.",
            traversable=False,
        ),
        EdgeDef(
            start=nk.GROUP,
            end=nk.COMPUTER,
            kind=ek.UPDATE_RECURRING_SCRIPTS,
            description="The group can create or update scripts on the target.",
            traversable=True,
        ),
        EdgeDef(
            start=nk.GROUP,
            end=nk.TENANT,
            kind=ek.CREATE_API_ROLES,
            description="The group can create API Roles in the Jamf tenant.",
            traversable=False,
        ),
        EdgeDef(
            start=nk.GROUP,
            end=nk.TENANT,
            kind=ek.UPDATE_API_ROLES,
            description="The group can update API Roles in the Jamf tenant.",
            traversable=False,
        ),
        EdgeDef(
            start=nk.GROUP,
            end=nk.TENANT,
            kind=ek.CREATE_API_CLIENT_AND_CREATE_ROLE,
            description="The group can create API clients and roles in the Jamf tenant.",
            traversable=True,
        ),
        EdgeDef(
            start=nk.GROUP,
            end=nk.TENANT,
            kind=ek.CREATE_API_CLIENT_AND_UPDATE_ROLE,
            description="The group can create API clients and update roles in the Jamf tenant.",
            traversable=True,
        ),
        EdgeDef(
            start=nk.GROUP,
            end=nk.TENANT,
            kind=ek.CREATE_API_CLIENT_AND_ASSIGN_ROLE,
            description="The group can create API clients and assign roles in the Jamf tenant.",
            traversable=True,
        ),
        EdgeDef(
            start=nk.GROUP,
            end=nk.TENANT,
            kind=ek.UPDATE_API_CLIENT_AND_UPDATE_ROLES,
            description="The group can update API clients and update roles in the Jamf tenant.",
            traversable=False,
        ),
        EdgeDef(
            start=nk.GROUP,
            end=nk.TENANT,
            kind=ek.UPDATE_API_CLIENT_AND_CREATE_ROLES,
            description="The group can update API clients and create roles in the Jamf tenant.",
            traversable=False,
        ),
        EdgeDef(
            start=nk.GROUP,
            end=nk.TENANT,
            kind=ek.UPDATE_API_CLIENT_AND_ASSIGN_ROLE,
            description="The group can update API clients and assign roles in the Jamf tenant.",
            traversable=False,
        ),
        EdgeDef(
            start=nk.GROUP,
            end=nk.SSO_INTEGRATION,
            kind=ek.UPDATE_SSO_SETTINGS,
            description="The group can update SSO settings in the Jamf tenant.",
            traversable=True,
        ),
    ],
)
class Group(JAMFAsset):
    """JAMF group resource parsed into a Pydantic model.

    Parses the raw JAMF group payload and exposes OpenGraph Node and Edges via
    the `as_node` and `edges` properties.

    Args:
        JAMFAsset (JAMFAsset): Base class providing OpenGraph node/edge exports.
    """

    id: int
    name: str
    access_level: str
    privilege_set: str
    site: Site
    privileges: Privilege | None = None
    members: list[User]
    site: Site
    members: list[User]

    @property
    def as_node(self):
        properties = GroupProperties(
            id=self.id,
            name=self.name,
            displayname=self.name,
            tenant=self.tenant_id,
            tier=1,
            site_id=str(self.site.id) if self.site else "-1",
            access_level=self.access_level,
            privilege_objects=self.privileges.jss_objects if self.privileges else [],
            privilege_actions=self.privileges.jss_actions if self.privileges else [],
            privilege_settings=self.privileges.jss_settings if self.privileges else [],
            privilege_set=self.privilege_set,
            environmentid=self.tenant_node_id,
        )
        return JAMFNode(kinds=[nk.GROUP], properties=properties)

    @property
    def _node_id(self) -> str:
        return self.as_node.id

    def _has_privilege(self, privilege: str) -> bool:
        return self.privileges is not None and privilege in self.privileges.jss_objects

    def _has_setting_privilege(self, privilege: str) -> bool:
        return self.privileges is not None and privilege in self.privileges.jss_settings

    @property
    def _is_admin(self) -> bool:
        return self.privilege_set == "Administrator" and self.access_level in (
            "Full Access",
            "Site Access",
        )

    def _target_computers(self):
        if self.access_level == "Site Access":
            return self._lookup.computers_by_site(str(self.site.id))
        return self._lookup.all_computers()

    @property
    def _contains_edge(self):
        yield Edge(
            kind=ek.CONTAINS,
            start=EdgePath(match_by="id", value=self.tenant_node_id),
            end=EdgePath(match_by="id", value=self._node_id),
            properties=EdgeProperties(traversable=True),
        )

    @property
    def _member_of_edges(self):
        for member in self.members:
            member_node_id = JAMFNode.guid(str(member.id), nk.ACCOUNT, self.tenant_id)
            yield Edge(
                kind=ek.MEMBER_OF,
                start=EdgePath(match_by="id", value=member_node_id),
                end=EdgePath(match_by="id", value=self._node_id),
                properties=EdgeProperties(traversable=True),
            )

    @property
    def _admin_to_edge(self):
        if self.access_level == "Full Access" and self.privilege_set == "Administrator":
            yield Edge(
                kind=ek.ADMIN_TO,
                start=EdgePath(match_by="id", value=self._node_id),
                end=EdgePath(match_by="id", value=self.tenant_node_id),
                properties=EdgeProperties(traversable=True),
            )

    @property
    def _admin_to_site_edges(self):
        if self.access_level == "Site Access" and self.privilege_set == "Administrator":
            site_node_id = JAMFNode.guid(str(self.site.id), nk.SITE, self.tenant_id)
            yield Edge(
                kind=ek.ADMIN_TO_SITE,
                start=EdgePath(match_by="id", value=self._node_id),
                end=EdgePath(match_by="id", value=site_node_id),
                properties=EdgeProperties(traversable=True),
            )

    @property
    def _create_accounts_edge(self):
        if not self._is_admin and self._has_privilege("Create Accounts"):
            yield Edge(
                kind=ek.CREATE_ACCOUNTS,
                start=EdgePath(match_by="id", value=self._node_id),
                end=EdgePath(match_by="id", value=self.tenant_node_id),
                properties=EdgeProperties(traversable=True),
            )

    @property
    def _update_accounts_edge(self):
        if not self._is_admin and self._has_privilege("Update Accounts"):
            yield Edge(
                kind=ek.UPDATE_ACCOUNTS,
                start=EdgePath(match_by="id", value=self._node_id),
                end=EdgePath(match_by="id", value=self.tenant_node_id),
                properties=EdgeProperties(traversable=True),
            )

    @property
    def _create_policies_edges(self):
        if not self._is_admin and self._has_privilege("Create Policies"):
            for (computer_id,) in self._target_computers():
                computer_node_id = JAMFNode.guid(
                    computer_id, nk.COMPUTER, self.tenant_id
                )
                yield Edge(
                    kind=ek.CREATE_POLICIES,
                    start=EdgePath(match_by="id", value=self._node_id),
                    end=EdgePath(match_by="id", value=computer_node_id),
                    properties=EdgeProperties(traversable=True),
                )

    @property
    def _update_policies_edges(self):
        if (
            not self._is_admin
            and self._has_privilege("Update Policies")
            and self._lookup.policies_exist()
        ):
            for (computer_id,) in self._target_computers():
                computer_node_id = JAMFNode.guid(
                    computer_id, nk.COMPUTER, self.tenant_id
                )
                yield Edge(
                    kind=ek.UPDATE_POLICIES,
                    start=EdgePath(match_by="id", value=self._node_id),
                    end=EdgePath(match_by="id", value=computer_node_id),
                    properties=EdgeProperties(traversable=True),
                )

    @property
    def _create_computer_extensions_edges(self):
        if not self._is_admin and self._has_privilege(
            "Create Computer Extension Attributes"
        ):
            for (computer_id,) in self._target_computers():
                computer_node_id = JAMFNode.guid(
                    computer_id, nk.COMPUTER, self.tenant_id
                )
                yield Edge(
                    kind=ek.CREATE_COMPUTER_EXTENSIONS,
                    start=EdgePath(match_by="id", value=self._node_id),
                    end=EdgePath(match_by="id", value=computer_node_id),
                    properties=EdgeProperties(traversable=True),
                )

    @property
    def _update_computer_extensions_edges(self):
        if (
            not self._is_admin
            and self._has_privilege("Update Computer Extension Attributes")
            and self._lookup.extension_attrs_exist()
        ):
            for (computer_id,) in self._target_computers():
                computer_node_id = JAMFNode.guid(
                    computer_id, nk.COMPUTER, self.tenant_id
                )
                yield Edge(
                    kind=ek.UPDATE_COMPUTER_EXTENSIONS,
                    start=EdgePath(match_by="id", value=self._node_id),
                    end=EdgePath(match_by="id", value=computer_node_id),
                    properties=EdgeProperties(traversable=True),
                )

    @property
    def _scripts_non_traversable_edge(self):
        if not self._is_admin and (
            self._has_privilege("Create Scripts")
            or self._has_privilege("Update Scripts")
        ):
            if self.access_level == "Site Access":
                site_node_id = JAMFNode.guid(str(self.site.id), nk.SITE, self.tenant_id)
                yield Edge(
                    kind=ek.SCRIPTS_NON_TRAVERSABLE,
                    start=EdgePath(match_by="id", value=self._node_id),
                    end=EdgePath(match_by="id", value=site_node_id),
                    properties=EdgeProperties(traversable=False),
                )
            else:
                yield Edge(
                    kind=ek.SCRIPTS_NON_TRAVERSABLE,
                    start=EdgePath(match_by="id", value=self._node_id),
                    end=EdgePath(match_by="id", value=self.tenant_node_id),
                    properties=EdgeProperties(traversable=False),
                )

    @property
    def _update_recurring_scripts_edges(self):
        if not self._is_admin and self._has_privilege("Update Scripts"):
            for (computer_id,) in self._lookup.recurring_policy_computers():
                computer_node_id = JAMFNode.guid(
                    str(computer_id), nk.COMPUTER, self.tenant_id
                )
                yield Edge(
                    kind=ek.UPDATE_RECURRING_SCRIPTS,
                    start=EdgePath(match_by="id", value=self._node_id),
                    end=EdgePath(match_by="id", value=computer_node_id),
                    properties=EdgeProperties(traversable=True),
                )

    @property
    def _create_api_roles_edge(self):
        if not self._is_admin and self._has_privilege("Create API Roles"):
            yield Edge(
                kind=ek.CREATE_API_ROLES,
                start=EdgePath(match_by="id", value=self._node_id),
                end=EdgePath(match_by="id", value=self.tenant_node_id),
                properties=EdgeProperties(traversable=False),
            )

    @property
    def _update_api_roles_edge(self):
        if not self._is_admin and self._has_privilege("Update API Roles"):
            yield Edge(
                kind=ek.UPDATE_API_ROLES,
                start=EdgePath(match_by="id", value=self._node_id),
                end=EdgePath(match_by="id", value=self.tenant_node_id),
                properties=EdgeProperties(traversable=False),
            )

    @property
    def _create_api_client_and_create_role_edge(self):
        if (
            not self._is_admin
            and self._has_privilege("Create API Integrations")
            and self._has_privilege("Create API Roles")
        ):
            yield Edge(
                kind=ek.CREATE_API_CLIENT_AND_CREATE_ROLE,
                start=EdgePath(match_by="id", value=self._node_id),
                end=EdgePath(match_by="id", value=self.tenant_node_id),
                properties=EdgeProperties(traversable=True),
            )

    @property
    def _create_api_client_and_update_role_edge(self):
        if (
            not self._is_admin
            and self._has_privilege("Create API Integrations")
            and self._has_privilege("Update API Roles")
            and self._lookup.roles_exist()
        ):
            yield Edge(
                kind=ek.CREATE_API_CLIENT_AND_UPDATE_ROLE,
                start=EdgePath(match_by="id", value=self._node_id),
                end=EdgePath(match_by="id", value=self.tenant_node_id),
                properties=EdgeProperties(traversable=True),
            )

    @property
    def _create_api_client_and_assign_role_edge(self):
        if (
            not self._is_admin
            and self._has_privilege("Create API Integrations")
            and self._lookup.roles_exist()
        ):
            yield Edge(
                kind=ek.CREATE_API_CLIENT_AND_ASSIGN_ROLE,
                start=EdgePath(match_by="id", value=self._node_id),
                end=EdgePath(match_by="id", value=self.tenant_node_id),
                properties=EdgeProperties(traversable=True),
            )

    @property
    def _update_api_client_and_update_roles_edge(self):
        if (
            not self._is_admin
            and self._has_privilege("Update API Integrations")
            and self._has_privilege("Update API Roles")
            and self._lookup.roles_exist()
            and self._lookup.clients_exist()
        ):
            yield Edge(
                kind=ek.UPDATE_API_CLIENT_AND_UPDATE_ROLES,
                start=EdgePath(match_by="id", value=self._node_id),
                end=EdgePath(match_by="id", value=self.tenant_node_id),
                properties=EdgeProperties(traversable=False),
            )

    @property
    def _update_api_client_and_create_roles_edge(self):
        if (
            not self._is_admin
            and self._has_privilege("Update API Integrations")
            and self._has_privilege("Create API Roles")
            and self._lookup.clients_exist()
        ):
            yield Edge(
                kind=ek.UPDATE_API_CLIENT_AND_CREATE_ROLES,
                start=EdgePath(match_by="id", value=self._node_id),
                end=EdgePath(match_by="id", value=self.tenant_node_id),
                properties=EdgeProperties(traversable=False),
            )

    @property
    def _update_api_client_and_assign_role_edge(self):
        if (
            not self._is_admin
            and self._has_privilege("Update API Integrations")
            and self._lookup.roles_exist()
            and self._lookup.clients_exist()
        ):
            yield Edge(
                kind=ek.UPDATE_API_CLIENT_AND_ASSIGN_ROLE,
                start=EdgePath(match_by="id", value=self._node_id),
                end=EdgePath(match_by="id", value=self.tenant_node_id),
                properties=EdgeProperties(traversable=False),
            )

    @property
    def _update_sso_settings_edges(self):
        if not self._is_admin and self._has_setting_privilege("Update SSO Settings"):
            sso_config_type = self._lookup.sso_config_type()
            if sso_config_type:
                sso_guid = JAMFNode.guid(
                    f"SSO-{sso_config_type}", nk.SSO_INTEGRATION, self.tenant_id
                )
                yield Edge(
                    kind=ek.UPDATE_SSO_SETTINGS,
                    start=EdgePath(match_by="id", value=self._node_id),
                    end=EdgePath(match_by="id", value=sso_guid),
                    properties=EdgeProperties(traversable=True),
                )
            else:
                for (account_id,) in self._lookup.all_accounts():
                    account_node_id = JAMFNode.guid(
                        str(account_id), nk.ACCOUNT, self.tenant_id
                    )
                    yield Edge(
                        kind=ek.UPDATE_SSO_SETTINGS,
                        start=EdgePath(match_by="id", value=self._node_id),
                        end=EdgePath(match_by="id", value=account_node_id),
                        properties=EdgeProperties(traversable=True),
                    )
                for (group_id,) in self._lookup.all_groups():
                    group_node_id = JAMFNode.guid(
                        str(group_id), nk.GROUP, self.tenant_id
                    )
                    yield Edge(
                        kind=ek.UPDATE_SSO_SETTINGS,
                        start=EdgePath(match_by="id", value=self._node_id),
                        end=EdgePath(match_by="id", value=group_node_id),
                        properties=EdgeProperties(traversable=True),
                    )

    @property
    def edges(self):
        yield from self._contains_edge
        yield from self._member_of_edges
        yield from self._admin_to_edge
        yield from self._admin_to_site_edges
        yield from self._create_accounts_edge
        yield from self._update_accounts_edge
        yield from self._create_policies_edges
        yield from self._update_policies_edges
        yield from self._create_computer_extensions_edges
        yield from self._update_computer_extensions_edges
        yield from self._scripts_non_traversable_edge
        yield from self._update_recurring_scripts_edges
        yield from self._create_api_roles_edge
        yield from self._update_api_roles_edge
        yield from self._create_api_client_and_create_role_edge
        yield from self._create_api_client_and_update_role_edge
        yield from self._create_api_client_and_assign_role_edge
        yield from self._update_api_client_and_update_roles_edge
        yield from self._update_api_client_and_create_roles_edge
        yield from self._update_api_client_and_assign_role_edge
        yield from self._update_sso_settings_edges
