from dataclasses import dataclass, field
from typing import Any

from openhound.core.asset import EdgeDef, NodeDef
from openhound.core.models.entries_dataclass import Edge, EdgePath, EdgeProperties
from pydantic import BaseModel, Field

from openhound_jamf.graph import JAMFAsset, JAMFNode, JAMFNodeProperties
from openhound_jamf.kinds import edges as ek
from openhound_jamf.kinds import nodes as nk
from openhound_jamf.main import app


class BaseUser(BaseModel):
    id: int
    name: str


class Computer(BaseModel):
    id: int
    name: str


class Peripherals(BaseModel):
    id: int
    name: str


class VPP(BaseModel):
    id: int
    name: str


class Mobile(BaseModel):
    id: int
    name: str


class ExtensionAtt(BaseModel):
    id: int
    name: str


class Site(BaseModel):
    id: int
    name: str


class UserGroup(BaseModel):
    size: int


class LDAPServer(BaseModel):
    id: int
    name: str


class Links(BaseModel):
    computers: list[Computer] = Field(default_factory=list)
    peripherals: Any = None
    mobile_devices: Any = None
    vpp_assignments: Any = None
    total_vpp_code_count: int = 0


@dataclass
class UserProperties(JAMFNodeProperties):
    """JAMF User node properties"""

    email: str
    phone_number: str
    full_name: str
    collected: bool = field(
        default=True, metadata={"description": "Collected/generated by OpenHound"}
    )


@app.asset(
    description="Jamf User asset. Returns a node representing a Jamf User and edges to assigned computers.",
    node=NodeDef(
        kind=nk.USER,
        description="Jamf User node",
        icon="user",
        properties=UserProperties,
    ),
    edges=[
        EdgeDef(
            start=nk.COMPUTER,
            end=nk.USER,
            kind=ek.ASSIGNED_USER,
            description="The specified user is assigned to the source computer.",
            traversable=True,
        ),
        EdgeDef(
            start=nk.USER,
            end=nk.ACCOUNT,
            kind=ek.MATCHED_EMAIL,
            description="The Jamf principal email attribute matched the Jamf account email indicating it is likely the same account.",
            traversable=True,
        ),
        EdgeDef(
            start=nk.USER,
            end=nk.ACCOUNT,
            kind=ek.MATCHED_NAME,
            description="The Jamf principal name or displayname attributes matched the Jamf account name.",
            traversable=True,
        ),
    ],
)
class User(JAMFAsset):
    id: int
    name: str
    full_name: str
    email: str
    email_address: str
    phone_number: str
    position: str
    managed_apple_id: str
    enable_custom_photo_url: bool
    custom_photo_url: str
    ldap_server: LDAPServer
    extension_attributes: list[ExtensionAtt]
    sites: list[Site]
    user_groups: UserGroup
    links: Links | None = None

    @property
    def as_node(self):
        properties = UserProperties(
            id=self.id,
            name=self.name,
            displayname=self.name,
            tenant=self.tenant_id,
            email=self.email,
            phone_number=self.phone_number,
            full_name=self.full_name,
            tier=1,
            environmentid=self.tenant_node_id,
        )
        return JAMFNode(kinds=[nk.USER], properties=properties)

    @property
    def _node_id(self) -> str:
        return self.as_node.id

    @property
    def _assigned_user_edges(self):
        if self.links:
            node_id = self._node_id
            for link in self.links.computers:
                computer_id = JAMFNode.guid(str(link.id), nk.COMPUTER, self.tenant_id)
                yield Edge(
                    kind=ek.ASSIGNED_USER,
                    start=EdgePath(match_by="id", value=computer_id),
                    end=EdgePath(match_by="id", value=node_id),
                    properties=EdgeProperties(traversable=True),
                )

    @property
    def _matched_email_edges(self):
        node_id = self._node_id
        for (account_id,) in self._lookup.accounts_by_email(self.email):
            account_node_id = JAMFNode.guid(str(account_id), nk.ACCOUNT, self.tenant_id)
            yield Edge(
                kind=ek.MATCHED_EMAIL,
                start=EdgePath(match_by="id", value=node_id),
                end=EdgePath(match_by="id", value=account_node_id),
                properties=EdgeProperties(traversable=True),
            )

    @property
    def _matched_name_edges(self):
        node_id = self._node_id
        for (account_id,) in self._lookup.accounts_by_name(self.name):
            account_node_id = JAMFNode.guid(str(account_id), nk.ACCOUNT, self.tenant_id)
            yield Edge(
                kind=ek.MATCHED_NAME,
                start=EdgePath(match_by="id", value=node_id),
                end=EdgePath(match_by="id", value=account_node_id),
                properties=EdgeProperties(traversable=True),
            )

    @property
    def edges(self):
        yield from self._assigned_user_edges
        yield from self._matched_email_edges
        yield from self._matched_name_edges
