from dataclasses import dataclass, field

from openhound.core.asset import EdgeDef, NodeDef
from openhound.core.models.entries_dataclass import Edge, EdgePath, EdgeProperties
from pydantic import BaseModel, Field

from openhound_jamf.graph import (
    JAMFAsset,
    JAMFAssignedUserEdgeProperties,
    JAMFNode,
    JAMFNodeProperties,
)
from openhound_jamf.kinds import edges as ek
from openhound_jamf.kinds import nodes as nk
from openhound_jamf.main import app


class BaseUser(BaseModel):
    id: int


class Computer(BaseModel):
    id: int


class Links(BaseModel):
    computers: list[Computer] = Field(default_factory=list)


@dataclass
class UserProperties(JAMFNodeProperties):
    """JAMF User node properties"""

    phone_number: str
    full_name: str
    email: str | None = None
    collected: bool = field(
        default=True, metadata={"description": "Collected/generated by OpenHound"}
    )


@app.asset(
    description="Jamf User asset. Returns a node representing a Jamf User and edges to assigned computers.",
    node=NodeDef(
        kind=nk.USER,
        description="Jamf User node",
        icon="user",
        properties=UserProperties,
    ),
    edges=[
        EdgeDef(
            start=nk.COMPUTER,
            end=nk.USER,
            kind=ek.ASSIGNED_USER,
            description="The specified user is assigned to the source computer.",
            traversable=True,
        ),
        EdgeDef(
            start=nk.USER,
            end=nk.ACCOUNT,
            kind=ek.MATCHED_EMAIL,
            description="The Jamf principal email attribute matched the Jamf account email indicating it is likely the same account.",
            traversable=True,
        ),
        EdgeDef(
            start=nk.USER,
            end=nk.ACCOUNT,
            kind=ek.MATCHED_NAME,
            description="The Jamf principal name or displayname attributes matched the Jamf account name.",
            traversable=True,
        ),
    ],
)
class User(JAMFAsset):
    id: int
    name: str
    full_name: str
    email: str | None = None
    phone_number: str
    links: Links | None = None

    @property
    def as_node(self):
        properties = UserProperties(
            id=self.id,
            name=self.name,
            displayname=self.name,
            tenant=self.tenant_id,
            email=self.email,
            phone_number=self.phone_number,
            full_name=self.full_name,
            tier=1,
            environmentid=self.tenant_node_id,
        )
        return JAMFNode(kinds=[nk.USER], properties=properties)

    @property
    def _node_id(self) -> str:
        return self.as_node.id

    @property
    def _assigned_user_edges(self):
        if self.links:
            node_id = self._node_id
            for link in self.links.computers:
                computer_id = JAMFNode.guid(str(link.id), nk.COMPUTER, self.tenant_id)
                yield Edge(
                    kind=ek.ASSIGNED_USER,
                    start=EdgePath(match_by="id", value=computer_id),
                    end=EdgePath(match_by="id", value=node_id),
                    properties=JAMFAssignedUserEdgeProperties(
                        traversable=True,
                        match_type="hard",
                        confidence="high",
                        evidence_source="jamf_user_links_computers",
                        match_basis="jamf_native_id",
                        reason=(
                            "Jamf user details explicitly link this native user ID "
                            "to the computer ID."
                        ),
                    ),
                )

    @property
    def _matched_email_edges(self):
        if self.email:
            node_id = self._node_id
            for (account_id,) in self._lookup.accounts_by_email(self.email.strip()):
                account_node_id = JAMFNode.guid(
                    str(account_id), nk.ACCOUNT, self.tenant_id
                )
                yield Edge(
                    kind=ek.MATCHED_EMAIL,
                    start=EdgePath(match_by="id", value=node_id),
                    end=EdgePath(match_by="id", value=account_node_id),
                    properties=EdgeProperties(traversable=True),
                )

    @property
    def _matched_name_edges(self):
        node_id = self._node_id
        for (account_id,) in self._lookup.accounts_by_name(self.name):
            account_node_id = JAMFNode.guid(str(account_id), nk.ACCOUNT, self.tenant_id)
            yield Edge(
                kind=ek.MATCHED_NAME,
                start=EdgePath(match_by="id", value=node_id),
                end=EdgePath(match_by="id", value=account_node_id),
                properties=EdgeProperties(traversable=True),
            )

    @property
    def edges(self):
        yield from self._assigned_user_edges
        yield from self._matched_email_edges
        yield from self._matched_name_edges


@app.asset(
    description=(
        "Legacy-compatible Jamf computer inventory user evidence. Emits a soft "
        "AssignedUser relationship only when no native user/computer link exists."
    ),
    node=NodeDef(
        kind=nk.USER,
        description="Jamf Computer User node derived from inventory evidence",
        icon="user",
        properties=UserProperties,
    ),
    edges=[
        EdgeDef(
            start=nk.COMPUTER,
            end=nk.USER,
            kind=ek.ASSIGNED_USER,
            description=(
                "Computer inventory USER_AND_LOCATION data identifies an assigned "
                "user without a native Jamf user/computer link."
            ),
            traversable=True,
        )
    ],
)
class InventoryAssignedUser(JAMFAsset):
    computer_id: str
    username: str | None = None
    realname: str | None = None
    email: str | None = None
    phone: str | None = None

    @staticmethod
    def _nonblank(value: str | None) -> str | None:
        normalized = value.strip() if value is not None else ""
        return normalized or None

    @property
    def _identity(self) -> tuple[str, str] | None:
        for identity_field, value in (
            ("email", self.email),
            ("username", self.username),
            ("realname", self.realname),
        ):
            if normalized := self._nonblank(value):
                return identity_field, normalized
        return None

    @property
    def _match(self) -> tuple[int | str, str, str] | None:
        if email := self._nonblank(self.email):
            matches = self._lookup.users_by_email(email)
            if len(matches) == 1:
                return matches[0][0], "email", "medium"
        if username := self._nonblank(self.username):
            matches = self._lookup.users_by_name(username)
            if len(matches) == 1:
                return matches[0][0], "username", "low"
        return None

    @property
    def _synthetic_id(self) -> str:
        identity = self._identity
        if identity is None:
            raise ValueError("inventory user has no usable identity")
        return f"inventory:{identity[1].casefold()}"

    @property
    def _target_raw_id(self) -> int | str:
        match = self._match
        return match[0] if match else self._synthetic_id

    @property
    def _target_node_id(self) -> str:
        return JAMFNode.guid(str(self._target_raw_id), nk.USER, self.tenant_id)

    @property
    def as_node(self):
        identity = self._identity
        if identity is None or self._match:
            return None
        name = (
            self._nonblank(self.username)
            or self._nonblank(self.email)
            or self._nonblank(self.realname)
            or identity[1]
        )
        realname = self._nonblank(self.realname)
        return JAMFNode(
            kinds=[nk.USER],
            properties=UserProperties(
                id=self._synthetic_id,
                name=name,
                displayname=realname or name,
                tenant=self.tenant_id,
                email=self._nonblank(self.email),
                phone_number=self.phone or "",
                full_name=realname or name,
                tier=1,
                environmentid=self.tenant_node_id,
            ),
        )

    @property
    def edges(self):
        identity = self._identity
        if identity is None:
            return
        match = self._match
        if match and self._lookup.user_has_computer_link(match[0], self.computer_id):
            return

        if match:
            match_basis, confidence = match[1], match[2]
            reason = (
                "Legacy-compatible inference: Jamf computer inventory "
                f"USER_AND_LOCATION matched one collected Jamf user by {match_basis}; "
                "no native user/computer link was present."
            )
        else:
            match_basis = f"inventory_{identity[0]}"
            confidence = "low"
            reason = (
                "Legacy-compatible inference: Jamf computer inventory "
                "USER_AND_LOCATION identified a user that could not be hard-matched "
                "to a collected Jamf user ID."
            )

        yield Edge(
            kind=ek.ASSIGNED_USER,
            start=EdgePath(
                match_by="id",
                value=JAMFNode.guid(self.computer_id, nk.COMPUTER, self.tenant_id),
            ),
            end=EdgePath(match_by="id", value=self._target_node_id),
            properties=JAMFAssignedUserEdgeProperties(
                traversable=True,
                match_type="soft_legacy",
                confidence=confidence,
                evidence_source="jamf_computer_inventory_user_and_location",
                match_basis=match_basis,
                reason=reason,
            ),
        )
